board/urls.py
from importlib.resources import path

from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [

    path('', views.index,name='index'),
    path('<int:question_id>',views.detail, name='detail'),
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create')

    #path('index', views.test),
    #path('', views.index),
    #path('<int:question_id>',views.detail)
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls'))
    #path('url명',뷰에서 가져올 함수),
    #path('index', views.test),
    #path('', views.index),
    #path('<int:question_id>',views.detail)
]

board/models.py
from django.db import models

# Create your models here.
# subject : 질문의 제족
# content : 질문의 내용
# create_date : 질문을 작성한 일시

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject
    pass



# question : 질문
# content : 답변의 내용
# create_date : 답변을 작성한 일시
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    pass


# 질문 항목과 답변 항목 만들기
# ORM

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponse
from .models import Question, Answer
# Create your views here.

def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}

    return render(request, 'question_list.html',context)



def test(request):
    return render(request, 'test.html')

def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    return render(request, 'question_detail.html', {'question': question})

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    #question.answer_set.create(content =request.POST.get('content') , create_date=timezone.now())
    answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    answer.save()
    return redirect('board:detail', question_id=question.id)

templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/boardStyle.css' %}">
</head>
<body>
<h1>{{question.subject}}</h1>

    <div>
      {{question.content}}
    </div>


<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>


<form action="{% url 'board:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit" value="답변 등록하기">
    
</form>

</body>
</html>

templates/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css'%}">
</head>
<body>

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일자</th>

            </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'board:detail' question.id %}">{{question.subject}} </a>
                </td>
                <td>{{ question.create_date }}</td>

            </tr>
        {% endfor %}
        {% else %}
            <tr>
                <td>질문이 없습니다</td>
            </tr>

        {% endif %}
        </tbody>
    </table>
</div>     

</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test_page</title>
</head>
<body>
<h1>테스트 중입니다. </h1>
<h2> 템플릿과 장고 프레임워크의 구조에 대한 이해</h2>
<p>사과</p>
</body>
</html>